version: '3.8'
services: 
    mysqldb:
      image: mysql:8.0
      restart: unless-stopped
      env_file: ./.env
      environment:
        - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
        - MYSQL_DATABASE=$DB_NAME
      ports:
        - 3310:$DB_PORT
      volumes:
        - db:/data/db
    backend:
      depends_on:
        - mysqldb
      build: .
      restart: unless-stopped
      env_file: ./.env
      ports:
        - $PORT:$PORT
      environment:
        - DB_HOST=mysqldb
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
        - DB_NAME=$DB_NAME
        - DB_PORT=$DB_PORT
      stdin_open: true
      tty: true
volumes:
  db: